# Generated by Django 2.0.5 on 2018-06-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180626_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
