# Generated by Django 2.0.5 on 2018-06-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('classfiy', models.CharField(max_length=32)),
                ('ctime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='creattime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=64, null=True),
        ),
    ]
