# Generated by Django 2.0.5 on 2018-06-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180620_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='usergroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='classfiy',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='ctime',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='creattime',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
