# Generated by Django 2.0.5 on 2018-06-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180620_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='caption',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
