# Generated by Django 2.0.3 on 2018-04-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weibo',
            old_name='blog_date',
            new_name='weibo_date',
        ),
    ]
