# Generated by Django 2.0.3 on 2018-04-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180411_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authers',
            new_name='authors',
        ),
    ]
